"use client";
import {useEffect,useState} from "react";
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:4000";
const empty={full_name:"",phone:"",email:"",service_area:"",status:"ACTIVE"};
export default function Home(){
 const [agents,setAgents]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 async function load(){try{setLoading(true);const r=await fetch(`${API}/api/agents`);const d=await r.json();if(!r.ok)throw Error(d.message);setAgents(d)}catch(e){setMessage(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 function add(){setEditing(null);setForm(empty);setOpen(true);setMessage("")}
 async function edit(id){try{const r=await fetch(`${API}/api/agents/${id}`),d=await r.json();if(!r.ok)throw Error(d.message);setEditing(id);setForm({full_name:d.full_name,phone:d.phone,email:d.email,service_area:d.service_area,status:d.status});setOpen(true)}catch(e){setMessage(e.message)}}
 async function save(e){e.preventDefault();try{const r=await fetch(`${API}/api/agents${editing?`/${editing}`:""}`,{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.message);setOpen(false);setMessage(editing?"Agent updated.":"Agent created.");await load()}catch(e){setMessage(e.message)}}
 async function remove(id){if(!confirm("Delete this agent?"))return;try{const r=await fetch(`${API}/api/agents/${id}`,{method:"DELETE"});if(!r.ok){const d=await r.json();throw Error(d.message)}setMessage("Agent deleted.");await load()}catch(e){setMessage(e.message)}}
 return <main className="page"><header><div><h1>Delivery Agents</h1><p>Manage delivery agent records</p></div><button onClick={add}>Add Agent</button></header>{message&&<div className="message">{message}</div>}<section className="card">{loading?<p className="empty">Loading...</p>:agents.length===0?<p className="empty">No agents found.</p>:<div className="tableWrap"><table><thead><tr><th>Name</th><th>Phone</th><th>Email</th><th>Service Area</th><th>Status</th><th>Actions</th></tr></thead><tbody>{agents.map(a=><tr key={a.id}><td>{a.full_name}</td><td>{a.phone}</td><td>{a.email}</td><td>{a.service_area}</td><td><span className={`status ${a.status.toLowerCase()}`}>{a.status}</span></td><td><button className="small" onClick={()=>edit(a.id)}>Edit</button> <button className="small danger" onClick={()=>remove(a.id)}>Delete</button></td></tr>)}</tbody></table></div>}</section>{open&&<div className="overlay"><div className="modal"><div className="modalHead"><h2>{editing?"Edit Agent":"Add Agent"}</h2><button className="close" onClick={()=>setOpen(false)}>×</button></div><form onSubmit={save}><label>Full Name<input name="full_name" value={form.full_name} onChange={change} required/></label><label>Phone Number<input name="phone" value={form.phone} onChange={change} required/></label><label>Email Address<input type="email" name="email" value={form.email} onChange={change} required/></label><label>Service Area<input name="service_area" value={form.service_area} onChange={change} required/></label><label>Status<select name="status" value={form.status} onChange={change}><option>ACTIVE</option><option>INACTIVE</option></select></label><div className="formActions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button type="submit">{editing?"Update Agent":"Create Agent"}</button></div></form></div></div>}</main>
}
